server:
  port: 8099


eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8091/eureka}

  instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-clientegym-service
          uri: lb://ms-clientegym-service
          predicates:
            - Path=/clientegym/**
        - id: ms-membresia-service
          uri: lb://ms-membresia-service
          predicates:
            - Path=/membresia/**
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categoria/**, /producto/**
        - id: ms-pedido-service
          uri: lb://ms-pedido-service
          predicates:
            - Path=/pedido/**
